//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service._I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service._I18n.fa", typeof(fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال دسترسی با مشکل مواجه شد.
        /// </summary>
        internal static string AccessRight_Failed {
            get {
                return ResourceManager.GetString("AccessRight_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال دسترسی با موفقیت انجام شد.
        /// </summary>
        internal static string AccessRight_Success {
            get {
                return ResourceManager.GetString("AccessRight_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایگانی با مشکل مواجه شد.
        /// </summary>
        internal static string Archived_Failed {
            get {
                return ResourceManager.GetString("Archived_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایگانی با موفقیت انجام شد.
        /// </summary>
        internal static string Archived_Success {
            get {
                return ResourceManager.GetString("Archived_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور با موفقیت انجام شد.
        /// </summary>
        internal static string ChangePswd_success {
            get {
                return ResourceManager.GetString("ChangePswd_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظریه تاییدیه تحصیلی با اشکال انجام شد.
        /// </summary>
        internal static string Confirm_Answer_Failed {
            get {
                return ResourceManager.GetString("Confirm_Answer_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظریه تاییدیه تحصیلی با موفقیت انجام شد.
        /// </summary>
        internal static string Confirm_Answer_Success {
            get {
                return ResourceManager.GetString("Confirm_Answer_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی، نادرست میباشد.
        /// </summary>
        internal static string CurrentPswd_Invalid {
            get {
                return ResourceManager.GetString("CurrentPswd_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات با موفقیت انجام شد.
        /// </summary>
        internal static string general_Change_success {
            get {
                return ResourceManager.GetString("general_Change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج رکورد انجام شد .
        /// </summary>
        internal static string general_create_success {
            get {
                return ResourceManager.GetString("general_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با مشکل مواجه شد.
        /// </summary>
        internal static string general_delete_failure {
            get {
                return ResourceManager.GetString("general_delete_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد انجام شد.
        /// </summary>
        internal static string general_delete_success {
            get {
                return ResourceManager.GetString("general_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی برای درج وارد نشده است.
        /// </summary>
        internal static string general_insert_empty {
            get {
                return ResourceManager.GetString("general_insert_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج با مشکل مواجه شد.
        /// </summary>
        internal static string general_insert_failure {
            get {
                return ResourceManager.GetString("general_insert_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش با مشکل مواجه شد.
        /// </summary>
        internal static string general_update_failure {
            get {
                return ResourceManager.GetString("general_update_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رکورد  انجام شد.
        /// </summary>
        internal static string general_update_success {
            get {
                return ResourceManager.GetString("general_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید و تکرار آن با هم برابر نیستند.
        /// </summary>
        internal static string NewPassword_NotMatch {
            get {
                return ResourceManager.GetString("NewPassword_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاص کلمه عبور جدید با موفقیت انجام شد.
        /// </summary>
        internal static string ResetPswd_success {
            get {
                return ResourceManager.GetString("ResetPswd_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتوماسـیون اداری.
        /// </summary>
        internal static string SiteTitle1 {
            get {
                return ResourceManager.GetString("SiteTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال اطلاعات به وب سرویس تاییدیه تحصیلی با اشکال انجام شد.
        /// </summary>
        internal static string WebApi_Answer_Failed {
            get {
                return ResourceManager.GetString("WebApi_Answer_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال اطلاعات به وب سرویس تاییدیه تحصیلی با موفقیت انجام شد.
        /// </summary>
        internal static string WebApi_Answer_Success {
            get {
                return ResourceManager.GetString("WebApi_Answer_Success", resourceCulture);
            }
        }
    }
}
